apiVersion: v1
kind: Service
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  selector:
    app: petclinic
#    version: 1.0.1
  ports:
  - port: 80
    protocol: TCP
    targetPort: <CHANGE_THIS>
  type: NodePort
